Repository yiisoft/cache, pull requests merged in 2020-11, with the labels that each got.

#59 Update dev dependencies, pipelines, scrutinizer and fixed tests.
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .scrutinizer.yml
  README.md
  composer.json
  phpunit.xml.dist
Labels: status:code review

#63 Add CacheKeyNormalizer
  src/CacheKeyNormalizer.php
  tests/CacheKeyNormalizerTest.php
Labels: status:ready for merge

#66 Remove the restriction of key prefix to Cache
  src/Cache.php
  tests/ArrayCache/ArrayCacheDecoratorExtraTest.php
Labels: type:bug
